### ISSUE TITLE
Hoping to replace the original unavailable equipment

### ISSUE THREAD

**Issue by xzszlkd** [WittleWolfie/AutomaticBonusProgression#10]
Most of the equipment that uses the + attribute of this mod can not be used, meaning that there must be a trade-off and if it can be replaced, it will be great

**Comment by WittleWolfie** [comment]
That is the point of the automatic bonus progression system. You automatically receive those bonuses so there's no use for the items. (Technically the items can let you get bonuses at different levels, but in the TT rules those items just don't exist).

The goal is that you don't have to equip +stat items and can instead pick items for their special effects (of which are there are lots in game).

**Comment by xzszlkd** [comment]
It means discarding basic equipment attributes and replacing in-game attributes with upgrades in favor of items that have special effects?

**Comment by WittleWolfie** [comment]
Correct. So you can pick your weapon based on whatever special enchant Owlcat gave it + type, and the enhancement bonus will be increased automatically.

Using Legendary Weapons / Armor you can further enchant them with special effects. In general the goal was to let all the items Owlcat built shine instead of always using Cloak of Resistance, +5 Weapons / Armor, Stat Belts & Circlets, etc.

**Comment by xzszlkd** [comment]
Thanks for the answer. I understand!

**Comment by xzszlkd** [comment]
> 正确。因此，您可以根据猫头鹰猫赋予它+类型的特殊附魔来选择武器，并且增强加成将自动增加。
> 
> 使用传奇武器/盔甲，你可以用特殊效果进一步附魔它们。一般来说，目标是让猫头鹰建造的所有物品都闪耀，而不是总是使用抵抗斗篷、+5 武器/盔甲、统计腰带和圆圈等。

Thanks for the answer. I understand
