### ISSUE TITLE
Save not loading on 1.5; works fine when rolled back to 1.4

### ISSUE THREAD

**Issue by andaisq** [WittleWolfie/AutomaticBonusProgression#20]
[GameLogPrev.txt](https://github.com/user-attachments/files/16121662/GameLogPrev.txt)
[GameLogFullPrev.txt](https://github.com/user-attachments/files/16121664/GameLogFullPrev.txt)
As the title says. Running latest patch with 30 mods including ABP. Companions are all respecced via RespecMod and some stats are illegal, if that turns out to be somehow relevant.

**Comment by WittleWolfie** [comment]
This doesn't appear to be related to ABP, not sure why reverting helps. This could be a mod conflict.

The failure is caused by `974a033937494f6a80a87f98497c901a`, which is Sacred Summons in [Dark Codex](https://alterasc.github.io/DarkCodex/AllBlueprints.html).

You should either report to Dark Codex, or if you share your Player.log file for a failed attempt to load I might be able to help.

**Comment by andaisq** [comment]
[Player-prev.log](https://github.com/user-attachments/files/16121723/Player-prev.log)
Thanks for the prompt response! I didn't know which log to attach, lol. I will see about reporting to Dark Codex as well.

**Comment by WittleWolfie** [comment]
Based on that log I think you were seeing a temporary error and just restarting the game would have worked:

```
[DarkCodex] Version '1.7.0'. Loading.
[DarkCodex] [Exception] Exception - CodexLib was changed during runtime. Please restart.
System.Exception: CodexLib was changed during runtime. Please restart.
  at Shared.Main.ForceUpdateCodexLib (System.String modPath) [0x00153] in <bc1689fa49184d5e890be1205f557a1a>:0 
  at Shared.Main.Load (UnityModManagerNet.UnityModManager+ModEntry modEntry) [0x00037] in <bc1689fa49184d5e890be1205f557a1a>:0 
```

You should be fine to update to the latest version of ABP.

**Comment by andaisq** [comment]
Oh, thank you so much! I feel silly, but, well, better to feel silly.
